### ISSUE TITLE
Gini formula looks wrong (but works)

### ISSUE THREAD

**Issue by timotta** [open-risk/concentrationMetrics#4]
Looking for the formula here http://www.openriskmanual.org/wiki/Gini_Index 

![image](https://user-images.githubusercontent.com/7966495/39734576-4510d23e-524e-11e8-89a5-7342a1f3cc2a.png)

It seem that this code is wrong (but it works perfectly)
```python
(1.0 - 2.0 * np.multiply(i, weights).sum())/n + 1.0
```

I think the right code would be:
```python
(2.0 * np.multiply(i/n, weights).sum()) - (n - 1.0)/n
```
or following the other formula 

![image](https://user-images.githubusercontent.com/7966495/39734817-3597b01a-524f-11e8-908e-29147e98ca21.png)

```python
(n + 1.0)/n - (2.0 * np.multiply((n + 1 - i)/n, weights).sum())
```
Those two codes that match the formulas have a problem, they get the results as negative numbers

**Comment by open-risk** [comment]
Thanks for spotting this. The manual had the Gini formula with the opposite sign (both conventions are used). Modified the [manual documentation](http://www.openriskmanual.org/wiki/Gini_Index) so that it is consistent. The latest release includes some further tests (gini_test.py)

**Comment by open-risk** [comment]
Fixed in documentation
