### ISSUE TITLE
Document installation

### ISSUE THREAD

**Issue by Michael-E-Rose** [open-risk/concentrationMetrics#5]
This looks like a fine library! I think it can help me a lot.

Alas, I don't know how to get it. Your documentation doesn't state how to get it, it just starts with `import concentrationMetrics as cl`. But neither `concentrationMetrics` nor `concentrationmetrics` (package names should be all lower-case as per [PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)!) exist on PyPI. If you want users to download a script you should tell them.

**Comment by open-risk** [comment]
There is now a pre-release (0.5.0) with additional  functionality, datasets / tests and a package on PyPI that should simplify using the library. The API is still quite fluid (which was also a reason to delay releasing as a package). If you would try installing now and let me know of issues it would be great!

**Comment by Michael-E-Rose** [comment]
Great! I can install it from PyPI and the stuff I did previously is also working. But https://pypi.org/project/concentrationMetrics/ is empty and the package name is still not standard.

**Comment by open-risk** [comment]
Thats good to hear. Will fix the project description, not sure what happened there, it should have imported the description.rst file from the distribution. On the package name, following PEP conventions makes it quite unreadable (at least to me). In earlier versions is was "concentration_metrics" which is also not encouraged under PEP but in their infinite wisdom they don't provide a solution for long double named packages :-)

If you have any concrete use cases or other ideas for the library feel free to raise as issues, in the todo / roadmap I have a tentative sketch of the various directions where this could go

**Comment by open-risk** [comment]
Fixed on PyPI
