### ISSUE TITLE
Error instead of termination

### ISSUE THREAD

**Issue by Michael-E-Rose** [open-risk/concentrationMetrics#7]
If input criteria are not of the expected form (such as that the input is not a numpy array), the object throws a message and then _terminates the execution_. Neither is standard or desirable. Instead, the object should throw an exception (probably `AttributeError`) and nothing else.

**Comment by open-risk** [comment]
type and value checking has been streamlined. more in-depth testing will likely come in the future (after a new round of index additions and a likely api  redesign)
